version: '3.4'

networks:
  net_encrypt:
    driver: bridge

secrets:
  mysql_root_password:
    file: ./docker/secrets/mysql/mysql_root_password
  mysql_user:
    file: ./docker/secrets/mysql/mysql_user
  mysql_password:
    file: ./docker/secrets/mysql/mysql_password

services:
  container_encrypt:
    build:
      context: .
      dockerfile: ./docker/encrypt/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/encrypt
    environment:
      CONTAINER_MYSQL_HOST: "container_mysql"
      CONTAINER_MYSQL_PORT: "3306"
      CONTAINER_MYSQL_USER: "/run/secrets/mysql_user"
      CONTAINER_MYSQL_PASSWORD: "/run/secrets/mysql_root_password"
      # Memcached
      CONTAINER_MEMCACHED_HOST: "container_memcached"
      # Redis
      CONTAINER_REDIS_HOST: "container_redis"
      CONTAINER_REDIS_USER: "root"
      # RabbitMq
      CONTAINER_RABBITMQ_HOST: "container_rabbitmq"
      CONTAINER_RABBITMQ_USER: "encrypt"
      CONTAINER_RABBITMQ_PASS: "secret"
      CONTAINER_RABBITMQ_VHOST: "encrypt"
      #xdebug
      PHP_IDE_CONFIG: "serverName=192.168.0.26"
      XDEBUG_CONFIG: "remote_host=192.168.0.15 idekey=PHPSTORM"
    networks:
      - net_encrypt
    depends_on:
      - container_mysql
      - container_memcached
      - container_redis
      - container_rabbitmq
    secrets:
      - mysql_root_password
      - mysql_user

  container_mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql_root_password"
      MYSQL_USER_FILE: "/run/secrets/mysql_user"
      MYSQL_PASSWORD_FILE: "/run/secrets/mysql_password"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - net_encrypt
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password

  container_memcached:
    image: memcached
    networks:
      - net_encrypt

  container_rabbitmq:
    image: rabbitmq:3.6.1-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=encrypt
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_VHOST=encrypt
    networks:
      - net_encrypt

  container_redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - net_encrypt
