rabbit_mq_supervisor:
    supervisor_instance_identifier:     instance_name
    paths:
        workspace_directory:            '%kernel.root_dir%/supervisor/%kernel.environment%/'
        configuration_file:             '%kernel.root_dir%/supervisor/%kernel.environment%/supervisord.conf'
        pid_file:                       '%kernel.root_dir%/supervisor/%kernel.environment%/supervisord.pid'
        sock_file:                      '%kernel.root_dir%/supervisor/%kernel.environment%/supervisord.sock'
        log_file:                       '%kernel.root_dir%/supervisor/%kernel.environment%/supervisord.log'
        worker_configuration_directory: '%kernel.root_dir%/supervisor/%kernel.environment%/worker/'
        worker_output_log_file:         '%kernel.root_dir%/supervisor/%kernel.environment%/logs/%kernel.environment%.log'
        worker_error_log_file:          '%kernel.root_dir%/supervisor/%kernel.environment%/logs/%kernel.environment%.log'
    commands:
        rabbitmq_consumer:              rabbitmq:consumer
        rabbitmq_multiple_consumer:     user-specific-command:multiple-consumer
    consumer:
        general:
            messages:                   2     # consumer command option: messages to consume
            memory-limit:               32      # consumer command option: allowed memory for this process
            debug:                      true    # consumer command option: enable debugging
            without-signals:            true    # consumer command option: disable catching of system signals
            worker:
                count:                  1       # number of workers per consumer
                startsecs:              2       # supervisord worker option: seconds to consider program running
                autorestart:            true    # supervisord worker option: if supervisord should restarted program automatically
                stopsignal:             INT     # supervisord worker option: the signal used to kill the program
                stopasgroup:            true    # supervisord worker option: if whole process group should be stopped
                stopwaitsecs:           60      # supervisord worker option: seconds to wait after stop signal before sending kill signal
        individual:
            # override options for specific consumers. you can use the same options for any consumer as in consumer.general
            consumer_name_1:
                # […]
            consumer_name_2:
                # […]